SHOW roles;
SHOW GRANTS;

USE role ACCOUNTADMIN;

SHOW GRANTS TO ROLE ACCOUNTADMIN;

SHOW warehouses;

CREATE OR REPLACE WAREHOUSE my_wh
  WAREHOUSE_SIZE = 'XSMALL';


USE WAREHOUSE MY_WH;
ALTER WAREHOUSE MY_WH SUSPEND;

USE WAREHOUSE COMPUTE_WH;

-- Creating a dev database
CREATE DATABASE IF NOT EXISTS DEV_DB
    COMMENT = 'Development Database for training with Snowflake';

SHOW DATABASES;

USE DATABASE DEV_DB;

CREATE SCHEMA IF NOT EXISTS DEV_DB.SANDBOX;
USE SCHEMA DEV_DB.SANDBOX;

CREATE OR REPLACE TABLE DEV_DB.SANDBOX.ORDERS (
    order_id STRING PRIMARY KEY,
    customer_id STRING NOT NULL,
    order_date DATE NOT NULL,
    order_status STRING,
    amount DECIMAL (12,2),
    processed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Cleaned orders - typed/validated - ready for analysis';

DESCRIBE TABLE ORDERS;

SELECT * FROM DEV_DB.SANDBOX.ORDERS;


